---
title: "Introduction: What even is Cognitive Psychology?"
description: |
  Welcome to my new blog, BallBlog. 
  Today I am discussing a short understanding
  of the field "Cognitive Psychology".
author:
  - name: Robbie Ball 
    url: https://twitter.com/ElephantNeurons
    affiliation: CUNY Graduate Center
    affiliation_url: https://www.gc.cuny.edu/
date: 08-31-2020
bibliography: PSYC_73800.bib 
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

# Learn more about creating blogs with Distill at:
# https://rstudio.github.io/distill/blog.html

```

I think that it is important to keep in mind how new the field of 
Cognitive Psychology, let alone Psychology, is relative to most other sciences.
Considering how bizarre and primitive early methods of Psychology are (eg 
measuring skulls to determine intelligence), I see Cognitive Psychology as a 
huge step in the right direction toward accurately understanding cognition and 
our minds. At it's core, Cognitive Psychology is the study of the
unobservable processes that occur in the brain in order to produce behavior that
does not necessarily mirror sensory input sent to the brain. 

A good 
example of pinpointing an instance of cognition at work would be playing the 
video game 'Tetris.' As a shape falls down and needs to be fit optimally, your
brain visualizes potential outcomes of your decisions that have not happened 
yet. You have the visual input of your placed shapes and the currently falling
shape and an understanding that the falling shape should be placed optimally 
to not stack too high and lose the game. Somewhere, in your brain, you are 
working a cognitive process to problem-solve and play the game.

What happens in that cognitive process? I do not think anyone knows exactly.
I do think we can use the framework of Cognitive Psychology to further 
investigate. Whether that be through the lens of neuroscience, behavior, AI,
etc., we still have a lot of work to do to better understand what is going on.

I think about this subject often because my undergraduate degree was in 
Cognitive Science and nobody could ever really explain perfectly what 
Cognitive Science really was. The department even emailed us to ask how we
explained it (to our parents). I believe this is why I am pursuing further 
education in this related field. It is something we all know exists and can 
give an example of it happening, but we cannot see it happen or give a 
concrete definition of what it is.

